name = "SignedCholesky"
uuid = "50dbd362-918f-47d7-a50f-7fe6628962b9"
authors = ["Seth K Asante <seth.kurankyi@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ProfileView = "c46f51b8-102a-5cf2-8d2c-8597cb0e0da7"

[compat]
LinearAlgebra = "1.11.0"
ProfileView = "1.10.2"
